name: Detect secrets
on:
  pull_request:
  workflow_call:

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Detect secrets
        uses: alphagov/pay-ci/actions/detect-secrets@master
